name: Build go code

on:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  buildCode:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - os: linux
            arch: amd64
            binary_name: totp-linux-amd64

          - os: windows
            arch: amd64
            binary_name: totp-windows-amd64.exe

          - os: darwin
            arch: amd64
            binary_name: totp-mac-amd64

          - os: darwin
            arch: arm64
            binary_name: totp-mac-arm64
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version: "1.22"
          cache: true

      - name: Build binary for individual platform
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
          CGO_ENABLED: 0
        run: |
          echo "Building for $GOOS-$GOARCH"
          go build -v -trimpath -ldflags="-s -w" -o ${{ matrix.binary_name }} ./cmd/totp/

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.binary_name }}
          path: ${{ matrix.binary_name }}

  create-release:
    name: Create GitHub Release
    if: startsWith(github.ref, 'refs/tags/v')
    needs: buildCode
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download all build artifacts
        uses: actions/download-artifact@v4
        with:
          path: build-release

      - name: Create Release and Upload Assets
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            build-release/totp-linux-amd64/totp-linux-amd64
            build-release/totp-windows-amd64.exe/totp-windows-amd64.exe
            build-release/totp-mac-amd64/totp-mac-amd64
            build-release/totp-mac-arm64/totp-mac-arm64
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
